[server]
name = "rustykv"
version = "1.0.0"
description = "A simple server configuration"

[server.network]
host = "0.0.0.0"
port = 6379
root_user = "root"
root_password = "rootpassword"
user = "admin"
password = "securepassword"

[server.db]
path = "./.db/internal"
backup_path = "./.db/backup"
max_size = 2048
backup_interval = 3600
compression = true
enable_logging = true
